INSERT INTO easylogistic.estado (id_estado, estado, eliminada) VALUES (1, 'Aguascalientes', 0);
INSERT INTO easylogistic.estado (id_estado, estado, eliminada) VALUES (2, 'Baja California', 0);
INSERT INTO easylogistic.estado (id_estado, estado, eliminada) VALUES (3, 'Baja California Sur', 0);
INSERT INTO easylogistic.estado (id_estado, estado, eliminada) VALUES (4, 'Campeche', 0);
INSERT INTO easylogistic.estado (id_estado, estado, eliminada) VALUES (5, 'Coahuila de Zaragoza', 0);
INSERT INTO easylogistic.estado (id_estado, estado, eliminada) VALUES (6, 'Colima', 0);
INSERT INTO easylogistic.estado (id_estado, estado, eliminada) VALUES (7, 'Chiapas', 0);
INSERT INTO easylogistic.estado (id_estado, estado, eliminada) VALUES (8, 'Chihuahua', 0);
INSERT INTO easylogistic.estado (id_estado, estado, eliminada) VALUES (9, 'Distrito Federal', 0);
INSERT INTO easylogistic.estado (id_estado, estado, eliminada) VALUES (10, 'Durango', 0);
INSERT INTO easylogistic.estado (id_estado, estado, eliminada) VALUES (11, 'Guanajuato', 0);
INSERT INTO easylogistic.estado (id_estado, estado, eliminada) VALUES (12, 'Guerrero', 0);
INSERT INTO easylogistic.estado (id_estado, estado, eliminada) VALUES (13, 'Hidalgo', 0);
INSERT INTO easylogistic.estado (id_estado, estado, eliminada) VALUES (14, 'Jalisco', 0);
INSERT INTO easylogistic.estado (id_estado, estado, eliminada) VALUES (15, 'México', 0);
INSERT INTO easylogistic.estado (id_estado, estado, eliminada) VALUES (16, 'Michoacán de Ocampo', 0);
INSERT INTO easylogistic.estado (id_estado, estado, eliminada) VALUES (17, 'Morelos', 0);
INSERT INTO easylogistic.estado (id_estado, estado, eliminada) VALUES (18, 'Nayarit', 0);
INSERT INTO easylogistic.estado (id_estado, estado, eliminada) VALUES (19, 'Nuevo León', 0);
INSERT INTO easylogistic.estado (id_estado, estado, eliminada) VALUES (20, 'Oaxaca de Juárez', 0);
INSERT INTO easylogistic.estado (id_estado, estado, eliminada) VALUES (21, 'Puebla', 0);
INSERT INTO easylogistic.estado (id_estado, estado, eliminada) VALUES (22, 'Querétaro', 0);
INSERT INTO easylogistic.estado (id_estado, estado, eliminada) VALUES (23, 'Quintana Roo', 0);
INSERT INTO easylogistic.estado (id_estado, estado, eliminada) VALUES (24, 'San Luis Potosí', 0);
INSERT INTO easylogistic.estado (id_estado, estado, eliminada) VALUES (25, 'Sinaloa', 0);
INSERT INTO easylogistic.estado (id_estado, estado, eliminada) VALUES (26, 'Sonora', 0);
INSERT INTO easylogistic.estado (id_estado, estado, eliminada) VALUES (27, 'Tabasco', 0);
INSERT INTO easylogistic.estado (id_estado, estado, eliminada) VALUES (28, 'Tamaulipas', 0);
INSERT INTO easylogistic.estado (id_estado, estado, eliminada) VALUES (29, 'Tlaxcala', 0);
INSERT INTO easylogistic.estado (id_estado, estado, eliminada) VALUES (30, 'Veracruz de Ignacio de la Llave', 0);
INSERT INTO easylogistic.estado (id_estado, estado, eliminada) VALUES (31, 'Yucatán', 0);
INSERT INTO easylogistic.estado (id_estado, estado, eliminada) VALUES (32, 'Zacatecas', 0);