INSERT INTO easylogistic.estado (estado, eliminada) VALUES ('Aguascalientes', '0');
INSERT INTO easylogistic.estado (estado, eliminada) VALUES ('Baja California', '0');
INSERT INTO easylogistic.estado (estado, eliminada) VALUES ('Baja California Sur', '0');
INSERT INTO easylogistic.estado (estado, eliminada) VALUES ('Campeche', '0');
INSERT INTO easylogistic.estado (estado, eliminada) VALUES ('Coahuila de Zaragoza', '0');
INSERT INTO easylogistic.estado (estado, eliminada) VALUES ('Colima', '0');
INSERT INTO easylogistic.estado (estado, eliminada) VALUES ('Chiapas', '0');
INSERT INTO easylogistic.estado (estado, eliminada) VALUES ('Chihuahua', '0');
INSERT INTO easylogistic.estado (estado, eliminada) VALUES ('Distrito Federal', '0');
INSERT INTO easylogistic.estado (estado, eliminada) VALUES ('Durango', '0');
INSERT INTO easylogistic.estado (estado, eliminada) VALUES ('Guanajuato', '0');
INSERT INTO easylogistic.estado (estado, eliminada) VALUES ('Guerrero', '0');
INSERT INTO easylogistic.estado (estado, eliminada) VALUES ('Hidalgo', '0');
INSERT INTO easylogistic.estado (estado, eliminada) VALUES ('Jalisco', '0');
INSERT INTO easylogistic.estado (estado, eliminada) VALUES ('México', '0');
INSERT INTO easylogistic.estado (estado, eliminada) VALUES ('Michoacán de Ocampo', '0');
INSERT INTO easylogistic.estado (estado, eliminada) VALUES ('Morelos', '0');
INSERT INTO easylogistic.estado (estado, eliminada) VALUES ('Nayarit', '0');
INSERT INTO easylogistic.estado (estado, eliminada) VALUES ('Nuevo León', '0');
INSERT INTO easylogistic.estado (estado, eliminada) VALUES ('Oaxaca de Juárez', '0');
INSERT INTO easylogistic.estado (estado, eliminada) VALUES ('Puebla', '0');
INSERT INTO easylogistic.estado (estado, eliminada) VALUES ('Querétaro', '0');
INSERT INTO easylogistic.estado (estado, eliminada) VALUES ('Quintana Roo', '0');
INSERT INTO easylogistic.estado (estado, eliminada) VALUES ('San Luis Potosí', '0');
INSERT INTO easylogistic.estado (estado, eliminada) VALUES ('Sinaloa', '0');
INSERT INTO easylogistic.estado (estado, eliminada) VALUES ('Sonora', '0');
INSERT INTO easylogistic.estado (estado, eliminada) VALUES ('Tabasco', '0');
INSERT INTO easylogistic.estado (estado, eliminada) VALUES ('Tamaulipas', '0');
INSERT INTO easylogistic.estado (estado, eliminada) VALUES ('Tlaxcala', '0');
INSERT INTO easylogistic.estado (estado, eliminada) VALUES ('Veracruz de Ignacio de la Llave', '0');
INSERT INTO easylogistic.estado (estado, eliminada) VALUES ('Yucatán', '0');
INSERT INTO easylogistic.estado (estado, eliminada) VALUES ('Zacatecas', '0');